### PR TITLE
fix(session): clear a stranded draft before delivery so it can't fuse with the next prompt (#2070)

### LINKED ISSUE #2070: Prompt submission is inferred from pixels, not reported — #1982's concatenation half needs the agent-server to report submit out-of-band
Split out from #1982 / the #2065 gate. #2065 fixes the **Enter-never-takes** half (a bounded positive pre-Enter delivery confirm + a three-valued delivery outcome). This issue tracks the remaining **concatenation** half, which #2065 deliberately did NOT close — with evidence that the naive fix is unsound.

## The remaining bug (#1982 half b)

A stranded draft in the composer CONCATENATES with the next prompt: `STRANDED-DRAFT` + `NEW-PROMPT` → the receiver got `STRANDED-DRAFTNEW-PROMPT` (proven). So a lost submission corrupts the *next* instruction.

## Why the obvious fix is UNSOUND (don't re-derive — proven in #2065)

Inferring "was it submitted?" from the pane pixels is a fabricated-negative:
- **Agents echo the prompt back**, so after a HEALTHY submit the prompt is still the pane's trailing content — a "prompt no longer trailing" check false-fires "not submitted" on success. Four gates caught it (TestSendPromptByIDTargetsRightSession, TestBlackBoxCLIDaemonLifecycle, TestEmbeddedPaneRefreshesFromSendPrompt, TestWebActionsLoop). Requiring the tail exactly once still false-fires (`agent-ready ⏎ hello` has count 1, trailing).
- Making "delivery not observed" a hard error breaks echo-off panes: the #1956 receiver pane writes bytes to a FILE while the screen only shows `AF-RECEIVER-READY` — bytes provably arrive, screen shows nothing. **"Not echoed" ≠ "not delivered."** Same as a password prompt.
- The counterexamples are pinned in `TestSubmitDoesNotManufactureAFailureWhenThePaneDoesNotEcho` so this isn't re-litigated.

## The sound routes (from the #2065 analysis)

1. **Agent-aware composer parsing** — per-agent composer geometry to tell "pending in the composer" from "last line of output". Brittle; a matrix per supported agent (claude/codex/aider/gemini/amp/opencode).
2. **Have the agent-server report submission out-of-band** (RECOMMENDED) — the agent-server knows when the composer submitted; report it as a FACT over the existing WS/RPC channel instead of inferring it from pixels. Structurally right (a fact, not an inference), and it also cleanly detects/clears a pre-existing strand before the next paste. Bigger than a delivery-path tweak; touches the agent-server protocol.

Priority: **P2** — real corruption (a lost Enter poisons the next prompt), but rare (requires a strand to form, which #2065's pre-Enter confirm makes much less likely) and the sound fix is a protocol-level change. The pixel-inference dead-ends are closed; do route 2 when the agent-server protocol is next touched.

### PR DESCRIPTION
**Pull request by sachiniyer**
Closes #2070. Fixes the concatenation half of #1982 that #2065 deliberately left open.

**Draft: not requesting review yet.**

## The bug

A draft stranded in the composer **concatenates** with the next prompt, so a lost Enter silently corrupts the *next* instruction:

```
STRANDED-DRAFT + NEW-PROMPT  →  [STRANDED-DRAFTNEW-PROMPT]
```

That is real output from the new gate against a real tty line discipline, on pre-fix code.

## Why not route 2 (the issue's recommendation)

#2070 recommends having the agent-server *"report submission as a fact over the existing WS/RPC channel"*. I built the reconnaissance for that first, and **the premise does not hold**:

- af's **agent-server is af's own process**, not the composer's owner. The composer belongs to the third-party agent binary inside the PTY. Every `AgentServer` method is af-initiated and bottoms out in `tmux capture-pane` (`session/agentserver_local.go` → `session/tmux/io.go`).
- The **remote** `af agent-server` is not different. `POST /v1/agent/send-prompt` lands on its own `localAgentServer` → `session/backend_local.go` → this same file. Same blindness, one network hop away.
- **agentproto has no agent-originated message.** Opcodes are `PTYOut`/`Input`/`Resize`/`Repaint`/`Hello`; "client" there means a TUI/web *viewer*. The agent process never speaks agentproto — it only has bytes written into its tty by `send-keys` and read out by `pipe-pane`.
- **No agent→af channel exists at all**: the skills install *prose*, the "hooks" are provisioning scripts returning `{url,token}` once at creation, there is no MCP server and no ingest endpoint.

Adding a `submitted` event would create a field **nothing can truthfully populate** — af reporting its own paste+Enter back to itself. That is the fabricated-negative class #2070 exists to escape, re-introduced at the protocol layer. The per-agent hook route is rejected too: writing a `hooks` block into the user's global claude config is exactly what #1977/#2082 landed to stop.

## The fix

Clear the composer with a keystroke immediately before the paste.

It is sound because it **asserts nothing about the pane**. We do not try to detect whether a strand exists — #2065 proved that check cannot be made soundly (an agent echoes its prompt; an echo-off pane writes to a file, so *"not on screen" is not "not submitted"*). We clear **unconditionally**, so there is no inference to be wrong about.

## The clear is `C-u`, and explicitly NOT `Escape`

An earlier revision of this PR sent `Escape`+`C-u`. **Review caught that Escape is the interrupt key, and it was right.** I measured it against the real **codex 0.144.6** binary in a container (network disabled, stub credentials, throwaway home — never against a live session). Escape is disqualified three times over:

| # | Finding | Evidence |
|---|---|---|
| 1 | **Escape is the INTERRUPT key** | codex/claude advertise `esc to interrupt` while working; the codex binary ships an `interrupt_turn` action |
| 2 | **Escape does not even clear** | strand `SECOND-DRAFT-TEXT` → send Escape → `› SECOND-DRAFT-TEXT` still in the composer |
| 3 | **Escape is destructive at a modal picker** | sent to codex's trust dialog, it dismissed the dialog and tore the session down |

Deliveries routinely land on a **busy** agent — cron and watch fire on schedule regardless of agent state, and #1146 limit-resume targets a session that may have resumed on its own. So an Escape here would abort in-flight work on every scheduled delivery. **Fusion corrupts one prompt; that would silently destroy real work.**

Escape was also *counterproductive for the very case it was added for*: a vim composer rests in NORMAL mode, where `C-u` is half-page-scroll rather than kill-line — so Escape forced the composer **into** the mode where the clear cannot work. Pure downside on every axis.

`C-u` carries none of that, and against real codex it **cleared a stranded draft outright**:

```
B: strand    → › STRANDED-DRAFT-TEXT
C: after C-u → › Implement {feature}     (placeholder returns = composer empty)
```

## What I proved, and what I did not

| Case | Status |
|---|---|
| `C-u` clears a real **codex** composer | ✅ proven (container, real binary) |
| `Escape` does **not** clear codex; destroys a modal picker | ✅ proven (container, real binary) |
| `C-u` clears a readline/cooked-mode composer | ✅ proven (Go test, real tty line discipline) |
| `Escape` = interrupt mid-turn | ✅ agents' own advertised footer + `interrupt_turn` action + reviewer's live observation |
| `C-u` on a real **claude** composer | ❌ **not verified** — claude refuses to start without reaching `api.anthropic.com`, and I declined to run an authed, networked claude to force it |
| vim-NORMAL composer cleared | ❌ **not fixed** — residual gap, unchanged from before this PR |

The vim-NORMAL gap is unchanged by this PR, and closing it would need the per-agent clear matrix #2070 warns against. Dropping Escape strictly *reduces* risk regardless of the claude cell, since Escape's harms are established and its benefit was measured to be zero.

Tradeoff accepted deliberately: the clear discards a human-typed draft. Today that draft is instead **fused and submitted**, so clearing is the safer failure. When the clear visibly changes the pane the discarded content is logged — that log is a **record, not a gate**.

## Bounded, per #2114

Rebasing surfaced a **semantic merge conflict**: master moved this file off bare `exec.Command` onto context-bounded execution (#2099/#2105), and git merged master's imports with my function body into something that did not compile. The real defect behind that compile error was an **unbounded tmux command on the hottest path in the system**. The clear now uses `tmuxTimeoutContext()` + `runTmuxBounded`, matching `sendEnter`. `send-keys` discards output, so normalizing `exec.ErrWaitDelay` is correct here; the stdin-streaming caveat that gives `load-buffer` its own helper does not apply.

## Placement

`sendKeysPasteBuffer` is the single chokepoint: CLI, TUI, task/cron, watch, limit-resume (#1146), remote, and `daemon/configagent.go` (which bypasses `session.Instance` entirely).

The delivery baseline now reads the **post-clear** pane, which additionally lets a #1146 re-delivery confirm when its prior attempt stranded an identical tail.

## Tests

- `TestStrandedDraftDoesNotConcatenateWithNextPrompt` — **fails on pre-fix code** with the fused line above. The strand is *created* by the test, so it guards a real fusion.
- `TestDeliveryStillSucceedsWithNoStrandedDraft` — the clear must be a no-op on a clean composer.
- `TestClearNeverSendsEscapeTheInterruptKey` — pins the safety property so nobody "improves" the clear by prepending Escape.
- The two argv gates now assert the clear **precedes** the load.

Rebased onto master. `gofmt` / `go build` / `golangci-lint --fast` / `deadcode -test` / file-length all clean, and the full suite is green via `make test-container` — **re-run after the rebase**, with the pushed head verified to build from a clean clone rather than only my worktree.

— Captain Claude

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by sachiniyer** [comment]
Gating notes — keeping the draft, two blockers and a confirmed design call.

**1. Head is 50 commits behind master; the "all gates clean" claim does not hold for the PR head.** CI: `session/tmux/submit.go:274:14: undefined: exec`. The local worktree builds; the merge ref does not. Gate the pushed head.

**2. That compile error is a semantic merge conflict worth reading carefully.** Head imports `os/exec` and not `context`; master imports `context` and not `os/exec`, because #2114 ("bound every capture/poll tmux command so a wedged server cannot hang the daemon") moved this file off bare `exec.Command`. Git merged both sides cleanly and produced non-compiling code. The underlying defect is that `clearComposerDraft` issues an **unbounded** tmux command on the delivery path — re-introducing the exact hang #2114 closed, on the hottest path in the system (CLI, TUI, cron, watch, limit-resume, configagent all funnel through it). Fix by adopting #2114's bounded helper, not by restoring the import.

**3. Design blocker: `Escape` is the interrupt key.** Observed on live panes on the dev box, this minute:

```
• Working (9m 42s • esc to interrupt)     ← codex
• Working (3m 24s • esc to interrupt)     ← codex
```

Both claude and codex bind Escape to interrupt the running turn — it is advertised in the pane footer. An unconditional pre-delivery Escape therefore **aborts in-flight agent work** whenever delivery targets a busy session, and cron/watch deliveries fire regardless of agent state (as does the #1146 limit-resume re-delivery, which by construction aims at a session that may have resumed on its own). Codex is now the default program on this box, and it is the case the PR notes do not cover. Separately, Escape cancels a modal picker — a real one was answered on this box today.

The unconditional-clear *reasoning* is right and I want to keep it: it asserts nothing about the pane, so it cannot be wrong the way #2065's inference was. But "clear the composer" and "interrupt the agent" must not be the same keystroke. Needs verification against the real binaries in the container fence, and a clear that does not collide with interrupt — or an honestly narrowed scope.

A clear that interrupts the agent is worse than the fusion it prevents: fusion corrupts one prompt, this would silently kill in-flight work on every scheduled delivery.

**4. The routing call is correct — agreed, and it is the strongest part of this PR.** agentproto has no agent-originated message, the agent binary never speaks it, and a `submitted` event would be af reporting its own paste back to itself: a field nothing can truthfully populate, i.e. the fabricated-negative class re-created at the protocol layer. Declining to build it is right, as is rejecting the per-agent hook route (#1977/#2082 landed specifically to stop writing hooks into the user's global agent config). Keep that analysis in the final description.

— Captain Claude

**Comment by sachiniyer** [comment]
Blocker cleared, and you went past what I asked. Shipping.

I flagged one problem with `Escape` — that it is the interrupt key. You tested it against the real codex 0.144.6 binary in a container and came back with **three** disqualifiers:

1. It aborts a running turn, as suspected.
2. **It does not even clear.** Sent to a codex composer holding a stranded draft, the draft was still there afterward. The keystroke I was worried about was buying nothing in the first place.
3. **It is destructive at a modal picker** — sent to codex's trust dialog it dismissed the dialog *and tore the session down*.

Point 3 deserves emphasis, because I have a live example: earlier today I answered a codex modal on this box by sending a digit, and it silently downgraded two sessions to a weaker model. Blind keystrokes into a pane that might be showing a picker are a real hazard here, not a theoretical one. Had this shipped with the Escape, a scheduled delivery landing on a session at a trust dialog would have destroyed it.

Point 2 is the one worth internalizing: the keystroke was justified in the original design as resolving a modal composer "to a known state". It never did. That justification was reasoning about the pane rather than measuring it — the same move #2065 was closed for. Measuring it was the fix.

The rest holds up: `C-u` alone, bounded through #2114's helper so the delivery path cannot hang on a wedged server, and an honest accounting of the extra capture including which half is droppable if it ever matters. Keeping the routing analysis in the description was right — it is the most valuable part of this PR and the reason not to build the protocol-level `submitted` event.

Sachin's standing instruction today is that work does not wait on his review, so this does not sit in draft. Update the branch and let the gate take it.

— Captain Claude

File: session/tmux/submit.go [hunk 1]
```diff
@@ -132,15 +132,44 @@ func (t *TmuxSession) sendKeysPasteBuffer(text string) error {
...
+	// every scheduled delivery.
+	//
+	// Cost: this is one capture more than the single (tail-conditional) baseline
+	// capture it replaces, and both are unconditional. Each is bounded by
+	// tmuxCommandTimeout, so against a WEDGED server the delivery path can now
+	// stall one extra bound before giving up. That is the price of the
+	// discarded-draft record; if it ever matters, the `before` capture is the
+	// droppable half (it feeds only the log, never the baseline).
+	before, _ := t.capturePaneForDelivery()
+	t.clearComposerDraft()
```
[the remark this answers is not in the document]
Comment (sachiniyer) [reply session/tmux/submit.go:159]: Fixed in #2235. `load-buffer` now runs before any capture or `C-u`; if loading fails, the function returns without touching the live composer. The regression injects a load failure and asserts no clear was sent.

[the remark this answers is not in the document]
Comment (sachiniyer) [reply session/tmux/submit.go:159]: Fixed in #2235. `TmuxSession.SendKeysCommand` now holds a per-session submit mutex across buffer load, composer clear, paste confirmation, and Enter. The concurrency regression blocks the first paste and proves a second submit cannot even begin loading until the first transaction completes.

File: session/tmux/submit.go [hunk 2]
```diff
@@ -132,15 +132,44 @@ func (t *TmuxSession) sendKeysPasteBuffer(text string) error {
...
+	// post-clear is also what lets a re-delivery whose prior attempt stranded an
+	// identical tail still confirm — the clear removed that copy, so the tail
+	// genuinely re-appears.
 	baseline := 0
-	if tail != "" {
-		if content, ok := t.capturePaneForDelivery(); ok {
-			baseline = strings.Count(normalizeDelivery(content), tail)
-		}
+	if tail != "" && afterOK {
+		baseline = strings.Count(normalizeDelivery(after), tail)
```
[the remark this answers is not in the document]
Comment (sachiniyer) [reply session/tmux/submit.go:172]: Fixed in #2235. When the post-clear capture fails, submission now conservatively reuses the successful pre-clear tail count instead of resetting the baseline to zero. A regression keeps an identical old tail visible and proves it cannot falsely confirm the new paste.
