### PR TITLE
fix(session): refuse root handoff in the shared guard (#2436)

### LINKED ISSUE #2436: [Detail Bug] TUI allows handoff flow for reserved "root" session, then daemon rejects after confirmation
# Detail Bug Report

https://app.detail.dev/org_d0a388e8-ab25-4b0e-bf83-9421012703cd/bugs/bug_2ea37a40-3820-4c4b-8c97-cc89a03ec1ee

Introduced in [#2071](https://github.com/sachiniyer/agent-factory/pull/2071) by @sachiniyer on Jul 20, 2026

# Summary
- **Context**: The TUI's handoff handler opens an agent picker so the user can swap a session's agent; it validates the session before opening the picker to avoid wasting the user's interaction.
- **Bug**: The TUI does not check `session.IsReservedTitle()` before opening the handoff picker, so the daemon-managed root session can proceed through picker → confirm → daemon call, only to be rejected by the daemon's `IsReservedTitle` guard.
- **Actual vs. expected**: The user is allowed to pick an agent and confirm the handoff for the reserved "root" session, then receives an error. The TUI should reject the handoff before opening the picker, as its own comment states: "Guards run BEFORE the picker, not after the choice."
- **Impact**: The user wastes an interaction (pick agent → confirm → error) on a session that can never be handed off, which the code's own comment identifies as reading "as a bug."

# Code with Bug
```go
// app/handle_handoff.go
func (m *home) handleHandoff() (tea.Model, tea.Cmd) {
	selected := m.sidebar.GetSelectedInstance()
	if selected == nil || selected.IsCreating() {
		return m, nil
	}
	if err := selected.ValidateRuntimeAction(session.RuntimeActionHandoff); err != nil {
		return m, m.handleError(err)
	}
	if !selected.Capabilities().Handoff {
		return m, m.handleError(fmt.Errorf("session '%s' cannot be handed off: only local-worktree sessions can swap their agent", selected.Title))
	}
	// <-- BUG 🔴 missing IsReservedTitle guard, so picker opens for reserved "root" session
}
```

```go
// daemon/handoff.go
if err := instance.ValidateRuntimeAction(session.RuntimeActionHandoff); err != nil {
	return HandoffSessionResponse{}, err
}
if session.IsReservedTitle(instance.Title) {
	return HandoffSessionResponse{}, fmt.Errorf("session %q cannot be handed off", req.Title)
}
```

# Explanation
The TUI intends to run all eligibility guards before showing the handoff agent picker (per its own comment) to avoid a “pick → confirm → error” experience. However, `handleHandoff()` only checks runtime action validity and backend capabilities; it never rejects reserved titles. As a result, the reserved "root" session can enter the picker/confirm flow, and only fails later when the daemon enforces `session.IsReservedTitle`.

## Codebase Inconsistency
- The daemon always rejects handoff for reserved titles via `session.IsReservedTitle(instance.Title)`.
- The TUI explicitly documents that such guards should happen before the picker, but does not implement the reserved-title guard for handoff.

# Recommended Fix
Add a reserved-title guard to `handleHandoff()` before opening the picker:

```go
func (m *home) handleHandoff() (tea.Model, tea.Cmd) {
	selected := m.sidebar.GetSelectedInstance()
	if selected == nil || selected.IsCreating() {
		return m, nil
	}
	if session.IsReservedTitle(selected.Title) {
		return m, m.handleError(fmt.Errorf("session %q cannot be handed off", selected.Title))
	}
	if err := selected.ValidateRuntimeAction(session.RuntimeActionHandoff); err != nil {
		return m, m.handleError(err)
	}
	if !selected.Capabilities().Handoff {
		return m, m.handleError(fmt.Errorf("session '%s' cannot be handed off: only local-worktree sessions can swap their agent", selected.Title))
	}
	// ... rest of function
}
```

# History
This bug was introduced in commit 88cf8f4c. The original handoff feature implemented TUI guards for teardown state and backend capabilities, but omitted the `IsReservedTitle` guard that the daemon has always enforced. The TUI's own comment ("Guards run BEFORE the picker") documents the intended design, yet reserved-title rejection was never implemented client-side, leaving the picker UX exposed to the wasteful interaction pattern the comment explicitly calls out as "reading as a bug."

### PR DESCRIPTION
**Pull request by sachiniyer**
Fixes #2436.

## The bug

The TUI let the user open the handoff picker for the daemon-managed root agent, choose a target, and confirm the swap — and only then surfaced the daemon's refusal. `handleHandoff`'s own comment says guards run BEFORE the picker "not after the choice", because making the user pick and confirm something that cannot happen reads as a bug.

Verified live on current `master` before fixing — this report is not stale.

## Why it happened, and where the fix goes

The report recommends adding an `IsReservedTitle` check to `handleHandoff`. That works, but it makes the rule a *third* thing each caller has to remember, and forgetting it is precisely how this bug arose.

The rule was implemented once, in `daemon/handoff.go` — sitting directly beneath that function's own call into `ValidateRuntimeAction`. The TUI asks `ValidateRuntimeAction` and nothing else before opening its picker, so it could not see the rule and concluded root was eligible.

So the refusal moves into `ValidateRuntimeAction`'s handoff case: the question both callers already ask, and the same place the archived/lost/dead refusals already live. The TUI gains the guard with no new client-side check to keep in sync, and the daemon keeps refusing through the same predicate. Its standalone `IsReservedTitle` check is **removed** rather than left as a second copy that can drift from the first.

It is checked **first** among the handoff conditions, ahead of the in-flight-op check, because it is permanent. A busy row says "try again in a moment"; root will never become eligible, and sending the user back to retry something that cannot work is the worse of the two answers.

## A gap this uncovered

The daemon-level refusal **had no test at all** — the guard being relied on was never exercised. Removing it on the strength of "the predicate covers it" would have been trading one untested assumption for another, so it now has a test at the daemon boundary (`TestHandoffSession_RefusesTheReservedRootSession`), asserting the refusal *and* that the runtime was never touched. The move cannot quietly become a removal.

## Tests

All watched failing first:

| test | package | locks |
| --- | --- | --- |
| `TestHandleHandoff_RefusesReservedRootBeforePicker` | `app` | no picker, no dispatch, and the error names root |
| `TestHandleHandoff_RefusesReservedRootRegardlessOfCase` | `app` | `"Root"` is still reserved |
| `TestHandleHandoff_AllowsSessionNamedLikeRoot` | `app` | control — `"rootcause"` still hands off |
| `TestRuntimeAction_HandoffRejectsTheReservedTitle` | `session` | the shared predicate, incl. `" ROOT "` variants |
| `TestHandoffSession_RefusesTheReservedRootSession` | `daemon` | end-to-end refusal, runtime untouched |

The root fixture is otherwise perfectly eligible — live, started, no in-flight op, backend advertises `Handoff` — so the title is doing all the work. Case variants are covered because `IsReservedTitle` matches case-insensitively on the trimmed title, and a guard comparing against the literal would route `" ROOT "` around a rule the daemon still enforces.

## Adjacent-call-site audit

Three other daemon sites pair `IsReservedTitle` with a lifecycle guard. Examined all three; folding them in was deliberately declined:

- **`daemon/restore.go:44`** — the closest structural match (same `ValidateRuntimeAction` + separate reserved check). Excluded because it has no equivalent symptom: `handleRestore` is a single keypress with **no confirmation step**, so there is no picker or confirm interaction to waste. Its refusal is also about the ensure loop owning root, not about the action being meaningless. Changing restore semantics with no reported symptom and no test proving a wasted interaction would widen this PR into a behavior change.
- **`daemon/archive.go:54`** — archive is not a `RuntimeAction`, so it does not route through this predicate at all; a different mechanism.
- **`daemon/manager_sessions.go:217`** — not a guard; it records kill intent for the self-heal delay (#1223).

## Gate

- `gofmt -l .` clean · `go build ./...` clean
- `golangci-lint run --timeout=3m --fast` clean
- `deadcode -test ./...` clean
- `scripts/lint-file-length.sh` passed (1001 files)
- `./session/... ./app/... ./daemon/...` green
- Full suite via `make test-container` on the pushed head — SHA in a follow-up comment

## Review

The codex GitHub app is rate-limited until Jul 28. Requesting once; if it stays silent I'll say so explicitly rather than letting green checks imply a review, and Captain Claude reviews this exact head before merge.

— Captain Claude

### CODE REVIEW

**Comment by sachiniyer** [comment]
## Gate — head `1302fffd0fae3324f1115991c336f6909ab33b09`

Full suite via `make test-container`, run on the pushed head above. **All packages green**, including the three this change touches:

```
ok  	github.com/sachiniyer/agent-factory/session	36.298s
ok  	github.com/sachiniyer/agent-factory/app	127.829s
ok  	github.com/sachiniyer/agent-factory/daemon	184.483s
```

Static gates on the same tree:

| gate | result |
| --- | --- |
| `gofmt -l .` | clean |
| `go build ./...` | clean |
| `golangci-lint run --timeout=3m --fast` | clean |
| `deadcode -test ./...` | clean |
| `scripts/lint-file-length.sh` | passed (1001 files, 0 grandfathered) |

All five new tests were watched failing before the fix. The two `app` tests failed on `state = 12` (the picker had opened) against the expected `0`; the `session` predicate test failed with "handoff accepted the reserved root title".

### On the TUI play-test gate

Not driven by hand, and saying so rather than skipping quietly. The change's whole effect is that a keypress on one specific row now shows an error instead of an overlay, and the three `app`-level tests assert exactly that against the real handler — including the control case proving an ordinary session still opens the picker. A manual pass would re-observe what those already pin.

@codex review

**Comment by sachiniyer** [comment]
## Review status: NOT reviewed — do not merge on my say-so

Saying this explicitly rather than letting green checks imply a review happened.

The codex GitHub app was requested and **declined**, twice — once on its own trigger when the PR opened, and once on my explicit `@codex review`. Both times it answered with the same thing:

> You have reached your Codex usage limits for code reviews.

That is the Jul 28 freeze. So there is **no review verdict on this head**, and bot silence here is a refusal, not a pass.

What is actually established on this head:

- required checks green (Deploy skipped, which does not gate)
- full `make test-container` suite green, run on the pushed SHA
- all four static gates clean
- the regression test watched failing before the fix

What is **not** established: a second pair of eyes on the change itself. This needs Captain Claude's independent review (claude-subagent or codex-CLI) on this exact SHA before it merges. I am not merging it.

— Captain Claude
